name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release (e.g., 0.0.1)'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.7'

      - name: Download ytdlgo.go
        run: |
          echo "Downloading ytdlgo.go..."
          cp ytdlgo.go $GITHUB_WORKSPACE/

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          go mod init ytdlgo
          go get github.com/kkdai/youtube/v2
          go get github.com/schollz/progressbar/v3

      - name: Build the application
        run: |
          echo "Building the application..."
          go build -o ytdlgo ytdlgo.go

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            (AUTOGENERATED) This release includes the latest version of ytdlgo.
          files: |
            ytdlgo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
